#!/usr/bin/env bash
# script that configure an nginx server to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "93i redirect" /etc/nginx/sites-enabled/default
sudo service nginx restart 
