#!/usr/bin/env bash
# script that configure a nginx server to have a custom header
# with certain requirement.

hostname=$(hostname)
sudo apt-get -y update
sudo apt-get -y install nginx
# Configure Nginx
HOST="add_header X-Served-By $hostname;"
sudo sed -i "51s|.*|$HOST|" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
