#!/usr/bin/env bash
# script that configure a nginx server to have a custom header
# with certain requirement.

hostname=$(hostname)
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une error_page" > /var/www/html/custom_404.html
echo "server {
     listen 80 default_server;
     listen [::]:80 default_server;
 
     root /var/www/html;
 
     # Add index.php to the list if you are using PHP
     index index.html index.htm index.nginx-debian.html;
 
     server_name _;
 
     location / {
         # First attempt to serve request as file, then
         # as a directory, then fall back to displaying a 404.
         try_files \$uri \$uri/ =404;
     }
 
     error_page 404 /custom_404.html;
     location = /custom_404.html {
         root /var/www/html;
         internal;
     }
 
     location /redirect_me {
         return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
     }
 
     add_header X-Served-By $host_name;
 
 }
 " > /etc/nginx/sites-enabled/default

#HOST="add_header X-Served-By $hostname;"
#sudo sed -i "51s|.*|$HOST|" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
