#!/usr/bin/env bash
# script that configure an nginx to run & listen to port 80.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt -y install curl
CONFIG="
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		try_files \$uri \$uri/ =404;
	}

}
"
echo "$CONFIG" > /etc/nginx/sites-enabled/default
sudo service nginx restart
