#!/usr/bin/env bash
# creates the file, displays its text indefinitely and catches signals
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -f "/var/run/myscript.pid"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "/var/run/myscript.pid"; exit 0' SIGQUIT

while true; do
	echo "To infinity and beyond"
done
