#!/usr/bin/env bash
# displays hours from (0 - 12) & minutes from (1 - 59)
hours=0
while [ $hours -le 12 ]; do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]; do
		echo $minutes
		((minutes++))
	done
	((hours++))
done | head -n 70

