#!/usr/bin/env bash
# gives the information about the school-file

file_path="school"
# check if the file exists
if [ -e "$file_path" ]; then
	echo "school file exists"
	# check if the file is empty or not
	if [ -s "$file_path" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	# check if the file is a regular file
	if [ -f "$file_path" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
