#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a configuration file for the redirection
echo "server {" | sudo tee /etc/nginx/sites-available/redirect_me
echo "    listen 80;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    server_name _;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    location /redirect_me {" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    }" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "}" | sudo tee -a /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart
