#!/usr/bin/env bash
# bash script that configures an ubuntu-server with certain requirements
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.2/127.0.0.1/ ~/hosts.new
#echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
